name:                idf-lint
version:             0.1.0.0
github:              "mitchpaulus/idf-lint"
license:             BSD3
author:              "Mitchell T. Paulus"
maintainer:          "Mitchell T. Paulus"
copyright:           "2020 Mitchell T. Paulus"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/idf-lint#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  idf-lint:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idf-lint

tests:
  idf-lint-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idf-lint
