//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.8
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Idd.g4 by ANTLR 4.8

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IddParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.8")]
[System.CLSCompliant(false)]
public interface IIddListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.idd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdd([NotNull] IddParser.IddContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.idd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdd([NotNull] IddParser.IddContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject([NotNull] IddParser.ObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject([NotNull] IddParser.ObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.object_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_header([NotNull] IddParser.Object_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.object_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_header([NotNull] IddParser.Object_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFields([NotNull] IddParser.FieldsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.fields"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFields([NotNull] IddParser.FieldsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.terminating_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminating_field([NotNull] IddParser.Terminating_fieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.terminating_field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminating_field([NotNull] IddParser.Terminating_fieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField([NotNull] IddParser.FieldContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField([NotNull] IddParser.FieldContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.field_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_id([NotNull] IddParser.Field_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.field_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_id([NotNull] IddParser.Field_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] IddParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] IddParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.object_properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_properties([NotNull] IddParser.Object_propertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.object_properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_properties([NotNull] IddParser.Object_propertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.field_properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_properties([NotNull] IddParser.Field_propertiesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.field_properties"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_properties([NotNull] IddParser.Field_propertiesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.object_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObject_property([NotNull] IddParser.Object_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.object_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObject_property([NotNull] IddParser.Object_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.field_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_property([NotNull] IddParser.Field_propertyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.field_property"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_property([NotNull] IddParser.Field_propertyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.min_fields_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMin_fields_statement([NotNull] IddParser.Min_fields_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.min_fields_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMin_fields_statement([NotNull] IddParser.Min_fields_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IddParser.units_based_on_field_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnits_based_on_field_statement([NotNull] IddParser.Units_based_on_field_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IddParser.units_based_on_field_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnits_based_on_field_statement([NotNull] IddParser.Units_based_on_field_statementContext context);
}
