name: Tests

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8
    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
    - name: Build
      run: dotnet build
    - name: Test NUnit
      run: dotnet test --filter FullyQualifiedName~tests.Tests --no-build --verbosity minimal tests/UnitTest1.cs
